### PR TITLE
docs: update Heart on Your Sleeve & Open Sourcerer

### PR DESCRIPTION
**Pull request by thuongtruong1009**

### CODE REVIEW

**Comment by Schweinepriester** [comment]
source? or link to a user who has them?

**Comment by thuongtruong1009** [comment]
> source? or link to a user who has them?

https://github.com/ParanoidUser/yolo/discussions/30

**Comment by Schweinepriester** [comment]
@Tynab has [not responded to me](https://github.com/Schweinepriester/github-profile-achievements/discussions/574#discussioncomment-5011712) asking for a source or proof, so at this time I believe their text is generated.

**Comment by ivansmialko** [comment]
Hi there! Just contacted with GitHub support about these badges, can you update the info?
image

**Comment by tundeloper** [comment]
awesome

**Comment by Schweinepriester** [comment]
fixed by https://github.com/Schweinepriester/github-profile-achievements/pull/738

**Pull request closed without merging**
