### PR TITLE
Update `Pair Extraordinaire` x2 and x3 numbers of merged PR

### PR DESCRIPTION
**Pull request by julthep**
Update `Pair Extraordinaire` x2 `Bronze` and x3 `Silver` numbers of merged PR.

### CODE REVIEW

**Comment by Schweinepriester** [comment]
Do you have any proof?

**Comment by julthep** [comment]
> Do you have any proof?

I have got mine for x2 and x3 and counted the number. 😅

**Comment by Imperfective** [comment]
this's correct information. thx Julthep. and I think, you want to gain the bedge of  Glod (X4), you have to merged pr over 100.

**Comment by Schweinepriester** [comment]
@kidonng, didn't you come to a [different conclusion before](https://github.com/Schweinepriester/github-profile-achievements/pull/113#discussion_r920218593)?
Or do you, @Rongronggg9, think you have >= 48 coauthored PRs? 🤔

**Comment by Rongronggg9** [comment]
Yes, I think I have. https://github.com/DIYgod/RSSHub has tons of forks with @pull[bot] configured.

**Comment by Schweinepriester** [comment]
Alright, thank you both, then we're going with those numbers. I'll remove the question mark - highly doubt it will be below that and we can change it once proven different.

Perhaps @julthep you can count again and let us know once you reach x4? :)

**Comment by julthep** [comment]
> Alright, thank you both, then we're going with those numbers. I'll remove the question mark - highly doubt it will be below that and we can change it once proven different.
> 
> Perhaps @julthep you can count again and let us know once you reach x4? :)

Yeah, I will try :) Currently, my latest coauthored PR is 41, so I guess that it may be 48, but someone said that it might be more than 100.

**Pull request merged**
