### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zigad**
Replacing black checkmarks with green ones. Green checkmarks are more visible on dark theme and it's easier to see if achievement is earnable or not.

### CODE REVIEW

**Comment by Schweinepriester** [comment]
Funny you mention that, because it's complicated as (raw) Emoji are different for everyone basically:
- https://emojipedia.org/check-mark/
- https://emojipedia.org/check-mark-button/

For example, for me ✔️ is still green, being mostly on Win10:

image

Also impulsively I didn't use [Check Mark Button ✅](https://emojipedia.org/check-mark-button/), because [Cross Mark ❌](https://emojipedia.org/cross-mark/) isn't a box then, a bit mismatching.
[Cross Mark Button ❎](https://emojipedia.org/cross-mark-button/) is a whole other mess…

But I'm open to the discussion, maybe you or anybody has anything to swing me to one pattern?
Maybe adding plain old Englisch "Yes" and "No" before whatever icon is useful anyway for accessibility reason and ease of understanding? Making the icon less important?
Or other symbols outside of Unicode Emoji? E.g. ☒ (https://unicode-table.com/en/2612/).

**Comment by yashash1511** [comment]
✅👍 any one of these for YES

❌👎⛔ any one of these for NO

**Comment by yassinbenmansour** [comment]
> ✅👍 any one of these for YES
> 
> ❌👎⛔ any one of these for NO
> 
> also see this [Specify theme context for images in Markdown GA ](https://github.blog/changelog/2022-08-15-specify-theme-context-for-images-in-markdown-ga/)

👌

**Comment by developernaimul** [comment]
test

**Pull request closed without merging**
