### PR TITLE
Update "YOLO" badge earning info

### PR DESCRIPTION
**Pull request by roypriyanshu02**

### CODE REVIEW

**Comment by roypriyanshu02** [comment]
> 

Glad to hear it

**Comment by eslamD7** [comment]
<html>
<body>


Closed an issue or a pull request within 5 min of opening
--


<br class="Apple-interchange-newline">
</body>
</html>

**Review by eslamD7 — COMMENTED** [review]
<html>
<body>


Closed an issue or a pull request within 5 min of opening
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by chenpotatos** [comment]
i am coming（maybe too late）

**Comment by MuhammadNizamani** [comment]
This seems good and why this PR is not merged yet?

**Comment by Schweinepriester** [comment]
> This seems good and why this PR is not merged yet?

It wasn't merged because of the auto sizing of the table decreasing the image sizes - I'll merge now to give the credit for improving, but I'll shorten it to an improved version compared to currently afterwards.

Thank you!

**Pull request merged**
