### PR TITLE
Changed info about Heart on "Your Sleeve" & "Open Sourcerer"

### PR DESCRIPTION
**Pull request by ivansmialko**

### CODE REVIEW

**Comment by ivansmialko** [comment]
Source: GitHub Support
image

**Comment by ivansmialko** [comment]
User mentioned here https://github.com/ParanoidUser/yolo/discussions/30 - Damovisa, is GitHub staff, so he have these new badges

**Comment by Schweinepriester** [comment]
Damn, good job getting that information! And thank you very much for not only letting me know but also opening the PR! 👏

RemoteJitteryGull-size_restricted

I will merge it to give you the attribution, but do know I'll make slight changes to the earnable column and while I'm at it probably split the table.

---

I deem those criteria very plausible and I trust you are acting in good faith, but want to say for the record that I acknowledge how easy it would be to fabricate the screenshot 0:-)

**Comment by ivansmialko** [comment]
Thank you for the response and merge!
I have no need to fabricate some badges criteria information, i was just curious to know how to do it, just as you :D 

Here's a full screenshot from a GitHub support page:
image

**Comment by Schweinepriester** [comment]
thank you! :)

curious about your screenshot oft that other table…? 👀 :D

**Pull request merged**
